### ISSUE TITLE
function arguments have esp layer parameter typedefs

### ISSUE THREAD

**Issue by bharadwaaj** [bytebeamio/ESP_app#2]
https://github.com/bytebeamio/ESP_app/blob/a5bd5d6b584c10e80096d44a8be8c37eb1439923/main/bytebeam_sdk.c#L19

https://github.com/bytebeamio/ESP_app/blob/a5bd5d6b584c10e80096d44a8be8c37eb1439923/main/bytebeam_sdk.c#L47

**Comment by prac13** [comment]
Replaced esp layer parameters with bytebeam parameters
